### ISSUE TITLE
기존에 이미 설치해서 쓰는 사람이 실행하면 어떻게 되나요?

### ISSUE THREAD

**Issue by doortts** [yona-projects/yona-install#2]
문득 궁금해져서.

**Comment by search5** [comment]
회사 도착하면 알려드릴게요. 운전중이라

2018년 10월 5일 (금) 오전 9:42, Suwon Chae <notifications@github.com>님이 작성:

**Comment by search5** [comment]
2가지 경우가 있을 수 있습니다.

1) 요나가 설치된 서버에 요나가 이용하는 MariaDB가 설치되어 있는 경우와 없는 경우

1.1) MariaDB가 설치되어 있는 경우
- 최신버전의 MariaDB가 설치되겠지만 MariaDB의 버전 차이로 인해 기존 프로그램이 제때 동작하지 않을 가능성이 높습니다.

1.2) MariaDB가 설치되어 있지 않은 경우
-요나피는 지정된 경로에 압축을 풀고 설정파일 수정까지만 자동으로 해줍니다. 프로그램을 직접 실행하지 않는 이상 큰 오류는 안 납니다. 근데 이것도 안해본거라 뭐라 말하기가 ㅋ

2) 요나가 어디에 설치되어 있는지 어떻게 압니까?
- 모릅니다. 현재 그 부분까지 고려하지 않았습니다. 이거 만든다고 밤샘한 저를 보면 알지 않겠습니까?

**Comment by doortts** [comment]
그렇다면 
기존에 MySQL이나 MariaDB가 설치되어 있는지 확인 한 번 하면 어떨까요?
https://serverfault.com/questions/69994/check-if-mysql-is-installed-on-server

그리고 Yona 가 이미 설치되었는지 여부는 직접 prompt 로 물어보면 어떨까요?

ㅎㅎ

**Comment by search5** [comment]
> 그렇다면
> 기존에 MySQL이나 MariaDB가 설치되어 있는지 확인 한 번 하면 어떨까요?
> https://serverfault.com/questions/69994/check-if-mysql-is-installed-on-server
> 
> 그리고 Yona 가 이미 설치되었는지 여부는 직접 prompt 로 물어보면 어떨까요?
> 
> ㅎㅎ

1) 요나 설치를 했는지 안했는지 모르는 사람이 있을 수 있습니다. 현재로선 요나피를 통해 설치한 경우만 관리를 예정하고 있습니다.
2) mysql이나 mariadb를 사용해도 mysql 명령이 PATH에 걸려있지 않을 가능성이 매우 높습니다. 포트 번호 한정하면 3306만을 찾을 수도 있지만 그 경우 다른 포트에서 MySQL이나 MariaDB가 동작할 수도 있기 때문에 자칫하면 1개 이상의 데이터베이스가 동작할 우려가 다분합니다.

**Comment by search5** [comment]
이 이슈는 일단 닫습니다.
